/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Lamppost(props) {
  const { nodes, materials } = useGLTF("/threeDModels/lamppost.glb");
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.375, 0]}>
        <pointLight 
            intensity={1000}
            decay={1.8}
            position={[0,2.7,0]}
            color="#f8fff1"
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/threeDModels/lamppost.glb");