/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function OscarStatuett(props: GroupProps) {
  const { nodes, materials }: { nodes: any, materials: any } = useGLTF("/threeDModels/oscar_statuett.glb");
  const image = useTexture('/images/sunny.jpg');
  image.flipY = false;
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.man.geometry}
        material={materials.gold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.photo}
      >
        <meshBasicMaterial map={image} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.gold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials.black}
      />
    </group>
  );
}

useGLTF.preload("/threeDModels/oscar_statuett.glb");