/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useCylinder } from "@react-three/cannon";
import { useGLTF, useTexture } from "@react-three/drei";

export function OscarStatuett(props: any) {
  const { nodes, materials }: { nodes: any, materials: any } = useGLTF("/threeDModels/oscar_statuett.glb");
  const [ref] = useCylinder(() => ({ args: [31.5,31.5,10, 12], type: 'Static', ...props }))
  const image = useTexture('/images/sunny.jpg');
  image.flipY = false;
  
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[0,-4.8,0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.man.geometry}
          material={materials.gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.photo}
        >
          <meshBasicMaterial map={image} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials.gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/threeDModels/oscar_statuett.glb");