/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function OscarText(props: GroupProps) {
  const { nodes, materials }: { nodes: any, materials: any } = useGLTF("/threeDModels/oscar_text.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OSCAR.geometry}
        material={materials["Material.006"]}
        position={[23.715, 0.005, 0.778]}
        rotation={[Math.PI / 2, 0, -3.14]}
        scale={1.759}
      />
    </group>
  );
}

useGLTF.preload("/threeDModels/oscar_text.glb");
