/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFBX, useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function VehicleSimpleBlender(props) {
  const car = useFBX("/threeDModels/car.fbx");
  return (
    <RigidBody {...props} dispose={null}>
      <mesh castShadow>
        <primitive object={car} />
      </mesh>
    </RigidBody>
  );
}

useGLTF.preload("/threeDModels/car.glb");
